[serviceapp.yml] remove make due to error
checking for enigma2... no
configure: error: Package requirements (enigma2) were not met:
Package 'enigma2', required by 'virtual:world', not found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables ENIGMA2_CFLAGS
and ENIGMA2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Error: Process completed with exit code 1.